import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

const recursive = Recursive({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { getUser } = getKindeServerSession();
	const user = await getUser();

	return (
		<html lang='en'>
			<body className={recursive.className}>
				<Navbar user={user} />
				<main className='min-h-screen'>{children}</main>
			</body>
		</html>
	);
}
