import type { Metadata } from 'next';

import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

import Navbar from '@/components/home/Navbar';

import { db } from '@/db';
import Footer from '@/components/home/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const Layout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const { getUser } = getKindeServerSession();
	const user = await getUser();

	const isAdmin = user?.email === process.env.ADMIN_EMAIL;
	const lists = await db.category.findMany({});

	return (
		<>
			<Navbar
				user={user}
				isAdmin={isAdmin}
				lists={lists}
				userIcon={user?.picture}
			/>
			<main>{children}</main>
			<Footer />
		</>
	);
};

export default Layout;
