import React from 'react';
import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';

import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

import Navbar from '@/components/home/Navbar';
import Footer from '@/components/home/Footer';

import { db } from '@/db';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const urbanist = Urbanist({ subsets: ['latin'] });

const Layout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const { getUser } = getKindeServerSession();
	const user = await getUser();

	const isAdmin = user?.email === process.env.ADMIN_EMAIL;
	const lists = await db.category.findMany({});

	return (
		<div className={urbanist.className}>
			<Navbar
				user={user}
				isAdmin={isAdmin}
				lists={lists}
				userIcon={user?.picture}
			/>
			<main>{children}</main>
			<Footer />
		</div>
	);
};

export default Layout;
