import type { Metadata } from 'next';

import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';

import Navbar from '@/components/home/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const Layout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const { getUser } = getKindeServerSession();
	const user = await getUser();
	const isAdmin = user?.email === process.env.ADMIN_EMAIL;

	return (
		<>
			<Navbar
				user={user}
				isAdmin={isAdmin}
			/>
			<main className='min-h-screen'>{children}</main>
		</>
	);
};

export default Layout;
